### ISSUE TITLE
Can you add some benchmarks?

### ISSUE THREAD

**Issue by daynin** [abtv/blook#2]
Hi! Thank you for that cool tool!

Can you compare it with similar tools which can be used for searching between patterns. For instance:

sed:
```
sed -rne '/<timestamp>/,/<timestamp>/ p' <file>
```

awk:
```
awk -v from="12:52:33" -v to="12:59:33" '$1>=from && $1<=to' foo.log
```

It would be great if you add a data and scripts for a benchmark into the repository. Thank you!

**Comment by abtv** [comment]
Hello, Sergey! Nice to hear from you. I've just added automated benchmarks and improved readme. Thanks for your comment!
